<a href="https://colab.research.google.com/github/thomaslu678/Praxis-Lab-25-26/blob/main/clean/17_VIT_Test_GL_NAIP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generate patches for park #0 (Green Loop)

In [ ]:
point_row_col_df_0 = grids_df.copy()

In [ ]:
point_row_col_df_0

,grid_id,row_index,col_index
0,92,91,0
1,93,92,0
2,94,93,0
3,95,94,0
4,96,95,0
...,...,...,...
7264,8106,5,75
7265,8107,6,75
7266,8108,7,75
7267,8214,5,76


In [ ]:
lookup_0 = {(r,c):pid for r,c,pid in zip(point_row_col_df_0.row_index, point_row_col_df_0.col_index, point_row_col_df_0.grid_id)}

In [ ]:
PATCH_SIZE = 5

In [ ]:
patches_0 = get_patches(point_row_col_df_0, PATCH_SIZE, lookup_0)
print(patches_0.shape)  # (#patches,5,5)

(5961, 5, 5)


In [ ]:
patches_0[0]

array([[ 92, 200, 308, 416, 524],
       [ 93, 201, 309, 417, 525],
       [ 94, 202, 310, 418, 526],
       [ 95, 203, 311, 419, 527],
       [ 96, 204, 312, 420, 528]])

In [ ]:
len(patches_0)

5961

# Generate patches for tree (not run, should be same as Green Loop)

In [ ]:
tree_row_col_df = pd.read_csv('/content/drive/MyDrive/Year 2/Fall 2025/HONOR 3700/Data/0/0_tree_row_col.csv')

In [ ]:
tree_row_col_df

,grid_id,row_index,col_index
0,92,91,0
1,93,92,0
2,94,93,0
3,95,94,0
4,96,95,0
...,...,...,...
6935,7691,22,71
6936,7692,23,71
6937,7693,24,71
6938,7694,25,71


In [ ]:
lookup = {(r,c):pid for r,c,pid in zip(tree_row_col_df.row_index, tree_row_col_df.col_index, tree_row_col_df.grid_id)}

In [ ]:
# Expect size to be an odd integer
def get_patches(df, size):

    patches = []

    for r,c in zip(df.row_index, df.col_index):

        valid = True
        patch = []

        for dr in range(-(size // 2) , (size // 2)+1):
            row_vals = []
            for dc in range(-(size // 2) , (size // 2)+1):

                key = (r+dr, c+dc)

                if key not in lookup:
                    valid = False
                    break

                row_vals.append(lookup[key])

            if not valid:
                break

            patch.append(row_vals)

        if valid:
            patches.append(patch)

    patches = np.array(patches)

    return patches

In [ ]:
PATCH_SIZE = 5

In [ ]:
patches_tree_0 = get_patches(tree_row_col_df, PATCH_SIZE)
print(patches_tree_0.shape)  # (#patches,5,5)

(5624, 5, 5)


In [ ]:
patches_tree_0[0].shape

(5, 5)

# Load datasets for tree patches

## Process zonal stats

In [ ]:
zonal_stats_df = pd.read_csv('/content/drive/MyDrive/Year 2/Fall 2025/HONOR 3700/Data/0/Trees ML/0_grid_zonal_statistics.csv')

In [ ]:
zonal_stats_df

,grid_id,row_index,col_index,red_count,red_sum,red_mean,green_count,green_sum,green_mean,blue_count,blue_sum,blue_mean,nir_count,nir_sum,nir_mean
0,92,91,0,2500,360989,144.395600,2500,364042,145.616800,2500,350403,140.161200,2500,347438,138.975200
1,93,92,0,2497,393822,157.718062,2497,398207,159.474169,2497,370796,148.496596,2497,435716,174.495795
2,94,93,0,2500,331540,132.616000,2500,338398,135.359200,2500,317191,126.876400,2500,424710,169.884000
3,95,94,0,2500,329664,131.865600,2500,336571,134.628400,2500,307081,122.832400,2500,438324,175.329600
4,96,95,0,2500,340133,136.053200,2500,344242,137.696800,2500,320666,128.266400,2500,419598,167.839200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7264,8106,5,75,2493,380147,152.485760,2493,380885,152.781789,2493,356467,142.987164,2493,370392,148.572804
7265,8107,6,75,2497,348732,139.660392,2497,359190,143.848618,2497,349611,140.012415,2497,317664,127.218262
7266,8108,7,75,2497,339403,135.924309,2497,348492,139.564277,2497,340254,136.265118,2497,332410,133.123748
7267,8214,5,76,2497,472292,189.143773,2497,477485,191.223468,2497,448381,179.567881,2497,496012,198.643172


In [ ]:
print(zonal_stats_df['red_count'].unique(),
      zonal_stats_df['green_count'].unique(),
      zonal_stats_df['blue_count'].unique(),
      zonal_stats_df['nir_count'].unique())

[2500 2497 2493 2498 2499 2496 2494 2495] [2500 2497 2493 2498 2499 2496 2494 2495] [2500 2497 2493 2498 2499 2496 2494 2495] [2500 2497 2493 2498 2499 2496 2494 2495]


In [ ]:
# zonal_stats_df = zonal_stats_df.drop(columns=['red_count', 'green_count', 'blue_count', 'nir_count'])

In [ ]:
# zonal_stats_df

## Process RGBALL

In [ ]:
rgbn_df = pd.read_csv('/content/drive/MyDrive/Year 2/Fall 2025/HONOR 3700/Data/0/Trees ML/0_rgbn_grid_radii.csv')

In [ ]:
rgbn_df

,RED,GREEN,BLUE,NIR,grid_id,radii_id
0,187,186,175,170,4713,1
1,187,186,174,170,4713,1
2,187,186,174,170,4713,1
3,187,186,174,170,4713,1
4,187,187,176,170,4713,1
...,...,...,...,...,...,...
573275,129,140,134,164,5706,110292
573276,108,123,115,183,5706,110292
573277,110,122,113,168,5706,110292
573278,165,168,158,171,5706,110292


In [ ]:
rgbn_df['grid_id'].isna().sum()

np.int64(0)

In [ ]:
# rgbn_df = rgbn_df.dropna()

In [ ]:
rgbn_df.isna().sum()

,0
RED,0
GREEN,0
BLUE,0
NIR,0
grid_id,0
radii_id,0


In [ ]:
rgbn_df['grid_id'].dtype

dtype('int64')

In [ ]:
# rgbn_df['grid_id'] = rgbn_df['grid_id'].astype(int)

In [ ]:
rgbn_df['grid_id']

,grid_id
0,4713
1,4713
2,4713
3,4713
4,4713
...,...
573275,5706
573276,5706
573277,5706
573278,5706


## Process radii df

In [ ]:
radii_df = pd.read_csv('/content/drive/MyDrive/Year 2/Fall 2025/HONOR 3700/Data/0/Trees ML/0_trees.csv')

In [ ]:
# radii_df['Vacant'].unique()

In [ ]:
# radii_df = radii_df.drop(columns=['Vacant'])

In [ ]:
radii_df

,radii_id,SPP,DBH,grid_id
0,1,Zelkova serrata,10,4714.0
1,4,Zelkova species,12,4712.0
2,5,Zelkova species,9,4712.0
3,7,Zelkova species,10,4711.0
4,8,Zelkova species,9,4711.0
...,...,...,...,...
4385,108092,Gleditsia triacanthos,13,8954.0
4386,110208,Tilia cordata,19,6798.0
4387,110290,Pyrus calleryana,2,5706.0
4388,110291,Pyrus calleryana,2,5706.0


In [ ]:
radii_df.isna().sum()

,0
radii_id,0
SPP,0
DBH,0
grid_id,143


In [ ]:
radii_df = radii_df.dropna()

In [ ]:
radii_df.isna().sum()

,0
radii_id,0
SPP,0
DBH,0
grid_id,0


## Process grids

In [ ]:
zonal_stats_df.columns

Index(['grid_id', 'row_index', 'col_index', 'red_count', 'red_sum', 'red_mean',
       'green_count', 'green_sum', 'green_mean', 'blue_count', 'blue_sum',
       'blue_mean', 'nir_count', 'nir_sum', 'nir_mean'],
      dtype='object')

In [ ]:
grids_df = zonal_stats_df[['grid_id', 'row_index', 'col_index']].copy()

In [ ]:
grids_df

,grid_id,row_index,col_index
0,92,91,0
1,93,92,0
2,94,93,0
3,95,94,0
4,96,95,0
...,...,...,...
7264,8106,5,75
7265,8107,6,75
7266,8108,7,75
7267,8214,5,76


In [ ]:
grids_df['grid_id'].isna().sum()

np.int64(0)

In [ ]:
np.min(grids_df['grid_id'])

92

In [ ]:
np.max(grids_df['grid_id'])

13709

## Process radii to grid id

In [ ]:
radii_df.columns

Index(['radii_id', 'SPP', 'DBH', 'grid_id'], dtype='object')

In [ ]:
radii_to_grid_df = radii_df[['radii_id', 'grid_id']].copy()

In [ ]:
radii_to_grid_df

,radii_id,grid_id
0,1,4714.0
1,4,4712.0
2,5,4712.0
3,7,4711.0
4,8,4711.0
...,...,...
4385,108092,8954.0
4386,110208,6798.0
4387,110290,5706.0
4388,110291,5706.0


In [ ]:
radii_to_grid_df['grid_id'].isna().sum()

np.int64(0)

In [ ]:
radii_to_grid_df['grid_id'].dtype

dtype('float64')

In [ ]:
radii_to_grid_df['grid_id'] = radii_to_grid_df['grid_id'].astype(int)

In [ ]:
radii_to_grid_df['grid_id'].dtype

dtype('int64')

## Confirm alignment

In [ ]:
# zonal_stats_df
# grids_df
# radii_df
# rgbn_df

In [ ]:
print("Grids: ", np.min(zonal_stats_df['grid_id']), np.max(zonal_stats_df['grid_id']))

Grids:  92 13709


In [ ]:
print("Grids: ", np.min(grids_df['grid_id']), np.max(grids_df['grid_id']))

Grids:  92 13709


In [ ]:
print("Radii: ", np.min(radii_df['radii_id']), np.max(radii_df['radii_id']))

Radii:  1 110292


In [ ]:
print("Grids: ", np.min(rgbn_df['grid_id']), np.max(rgbn_df['grid_id']))

Grids:  93 13601


In [ ]:
print("Radii: ", np.min(rgbn_df['radii_id']), np.max(rgbn_df['radii_id']))

Radii:  1 110292


In [ ]:
# 1. Check if all in zonal_stats_df
check1 = rgbn_df['grid_id'].isin(zonal_stats_df['grid_id']).all()

# 2. Check if all in grids_df
check2 = rgbn_df['grid_id'].isin(grids_df['grid_id']).all()

# 3. Final check: True if both conditions are met
all_present = check1 and check2

print(f"All present: {all_present}")

All present: True


In [ ]:
print(f"All present: {rgbn_df['radii_id'].isin(radii_df['radii_id']).all()}")

All present: False


In [ ]:
print(len(rgbn_df[rgbn_df['radii_id'].isin(radii_df['radii_id'])]))
print(len(rgbn_df[~rgbn_df['radii_id'].isin(radii_df['radii_id'])]))
print(len(rgbn_df))

573279
1
573280


In [ ]:
rgbn_df = rgbn_df[rgbn_df['radii_id'].isin(radii_df['radii_id'])]

In [ ]:
print(f"All present: {rgbn_df['radii_id'].isin(radii_df['radii_id']).all()}")

All present: True


In [ ]:
9290 in radii_df['radii_id']

False

In [ ]:
print(f"All present: {radii_df['radii_id'].isin(radii_to_grid_df['radii_id']).all()}")

All present: True


# Prepare processing tree patches

In [ ]:
# zonal_stats_df
# grids_df
# radii_df
# rgbn_df

In [ ]:
filtered_radii_df = radii_df[radii_df['radii_id'].isin(rgbn_df['radii_id'])].copy()

In [ ]:
radii_df

,radii_id,SPP,DBH,grid_id
0,1,Zelkova serrata,10,4714.0
1,4,Zelkova species,12,4712.0
2,5,Zelkova species,9,4712.0
3,7,Zelkova species,10,4711.0
4,8,Zelkova species,9,4711.0
...,...,...,...,...
4385,108092,Gleditsia triacanthos,13,8954.0
4386,110208,Tilia cordata,19,6798.0
4387,110290,Pyrus calleryana,2,5706.0
4388,110291,Pyrus calleryana,2,5706.0


In [ ]:
filtered_radii_df

,radii_id,SPP,DBH,grid_id
0,1,Zelkova serrata,10,4714.0
1,4,Zelkova species,12,4712.0
2,5,Zelkova species,9,4712.0
3,7,Zelkova species,10,4711.0
4,8,Zelkova species,9,4711.0
...,...,...,...,...
4385,108092,Gleditsia triacanthos,13,8954.0
4386,110208,Tilia cordata,19,6798.0
4387,110290,Pyrus calleryana,2,5706.0
4388,110291,Pyrus calleryana,2,5706.0


In [ ]:
filtered_radii_df.isna().sum()

,0
radii_id,0
SPP,0
DBH,0
grid_id,0


In [ ]:
filtered_radii_df['grid_id'].dtype

dtype('float64')

In [ ]:
filtered_radii_df['grid_id'] = filtered_radii_df['grid_id'].astype(int)

In [ ]:
filtered_radii_df['grid_id'].dtype

dtype('int64')

In [ ]:
filtered_radii_df

,radii_id,SPP,DBH,grid_id
0,1,Zelkova serrata,10,4714
1,4,Zelkova species,12,4712
2,5,Zelkova species,9,4712
3,7,Zelkova species,10,4711
4,8,Zelkova species,9,4711
...,...,...,...,...
4385,108092,Gleditsia triacanthos,13,8954
4386,110208,Tilia cordata,19,6798
4387,110290,Pyrus calleryana,2,5706
4388,110291,Pyrus calleryana,2,5706


## Process raw data into grid/radii id before/after

In [ ]:
# Initialize list to collect results
rows = []

In [ ]:
subset = rgbn_df[rgbn_df['radii_id'] == 1]

In [ ]:
subset

,RED,GREEN,BLUE,NIR,grid_id,radii_id
0,187,186,175,170,4713,1
1,187,186,174,170,4713,1
2,187,186,174,170,4713,1
3,187,186,174,170,4713,1
4,187,187,176,170,4713,1
...,...,...,...,...,...,...
111,220,214,198,198,4714,1
112,213,208,192,194,4714,1
113,206,202,187,189,4714,1
114,208,205,190,194,4714,1


In [ ]:
pix = subset[subset['grid_id'] == 4713]

In [ ]:
pix

,RED,GREEN,BLUE,NIR,grid_id,radii_id
0,187,186,175,170,4713,1
1,187,186,174,170,4713,1
2,187,186,174,170,4713,1
3,187,186,174,170,4713,1
4,187,187,176,170,4713,1
5,185,184,172,170,4713,1
6,186,185,173,170,4713,1
7,186,186,174,170,4713,1
8,187,186,174,172,4713,1
9,187,186,174,172,4713,1


In [ ]:
zonal_stats_df[zonal_stats_df['grid_id'] == 4713].iloc[0]

,6391
grid_id,4713.0000
row_index,68.0000
col_index,43.0000
red_count,2500.0000
red_sum,407892.0000
red_mean,163.1568
green_count,2500.0000
green_sum,416425.0000
green_mean,166.5700
blue_count,2500.0000


In [ ]:
pix['RED'].sum()

np.int64(7416)

In [ ]:
# Loop over each radius (fid)
for fid in filtered_radii_df['radii_id'].unique():

    # Subset rgbn_df for this radii_id
    subset = rgbn_df[rgbn_df['radii_id'] == fid]

    # Get unique grid_ids for this radius
    grid_ids = subset['grid_id'].unique()

    for gid in grid_ids:

        # Subset pixels for this grid_id + radii_id
        pix = subset[subset['grid_id'] == gid]

        # Get zonal stats row
        zs_row = zonal_stats_df[zonal_stats_df['grid_id'] == gid].iloc[0]

        # BEFORE values (means already computed)
        before_red = zs_row['red_mean']
        before_green = zs_row['green_mean']
        before_blue = zs_row['blue_mean']
        before_nir = zs_row['nir_mean']

        # ORIGINAL sums
        red_sum = zs_row['red_sum']
        green_sum = zs_row['green_sum']
        blue_sum = zs_row['blue_sum']
        nir_sum = zs_row['nir_sum']

        red_count = zs_row['red_count']
        green_count = zs_row['green_count']
        blue_count = zs_row['blue_count']
        nir_count = zs_row['nir_count']

        # Remove pixels inside radius
        removed_count = len(pix)

        # Subtract pixel values
        new_red_sum = red_sum - pix['RED'].sum()
        new_green_sum = green_sum - pix['GREEN'].sum()
        new_blue_sum = blue_sum - pix['BLUE'].sum()
        new_nir_sum = nir_sum - pix['NIR'].sum()

        # AFTER means
        after_red = new_red_sum / (red_count - removed_count) if red_count > 0 else None
        after_green = new_green_sum / (green_count - removed_count) if green_count > 0 else None
        after_blue = new_blue_sum / (blue_count - removed_count) if blue_count > 0 else None
        after_nir = new_nir_sum / (nir_count - removed_count) if nir_count > 0 else None

        # Append result
        rows.append({
            'grid_id': gid,
            'radii_id': fid,
            'before_red': before_red,
            'after_red': after_red,
            'before_green': before_green,
            'after_green': after_green,
            'before_blue': before_blue,
            'after_blue': after_blue,
            'before_nir': before_nir,
            'after_nir': after_nir
        })

In [ ]:
# Create final dataframe
result_df = pd.DataFrame(rows)

print(result_df.head())

   grid_id  radii_id  before_red   after_red  before_green  after_green  \
0     4713         1  163.156800  162.662876    166.570000   166.190089   
1     4714         1  176.186624  175.332369    176.368843   175.638280   
2     4712         4  163.377600  162.731011    165.856800   164.898028   
3     4713         4  163.156800  162.956698    166.570000   166.292594   
4     4712         5  163.377600  163.467695    165.856800   165.871613   

   before_blue  after_blue  before_nir   after_nir  
0   155.806400  155.464257  179.997600  179.901706  
1   165.299159  164.636627  180.563476  180.420835  
2   156.722800  155.711708  182.564000  180.994964  
3   155.806400  155.537030  179.997600  179.519628  
4   156.722800  156.484368  182.564000  181.899125  


In [ ]:
len(result_df['radii_id'].unique())

4099

In [ ]:
result_df

,grid_id,radii_id,before_red,after_red,before_green,after_green,before_blue,after_blue,before_nir,after_nir
0,4713,1,163.156800,162.662876,166.570000,166.190089,155.806400,155.464257,179.997600,179.901706
1,4714,1,176.186624,175.332369,176.368843,175.638280,165.299159,164.636627,180.563476,180.420835
2,4712,4,163.377600,162.731011,165.856800,164.898028,156.722800,155.711708,182.564000,180.994964
3,4713,4,163.156800,162.956698,166.570000,166.292594,155.806400,155.537030,179.997600,179.519628
4,4712,5,163.377600,163.467695,165.856800,165.871613,156.722800,156.484368,182.564000,181.899125
...,...,...,...,...,...,...,...,...,...,...
6182,6798,110208,132.549600,135.961933,136.632400,139.340462,132.030800,134.446108,141.544800,140.903764
6183,6906,110208,115.277600,115.754272,124.586400,124.966640,114.270000,114.456062,166.697600,167.005289
6184,5706,110290,182.357000,182.491341,185.326113,185.458317,182.846771,182.996375,171.239471,171.436569
6185,5706,110291,182.357000,182.570508,185.326113,185.512490,182.846771,183.055197,171.239471,171.325141


In [ ]:
zonal_stats_df[zonal_stats_df['grid_id'] == 4713]

,grid_id,row_index,col_index,red_count,red_sum,red_mean,green_count,green_sum,green_mean,blue_count,blue_sum,blue_mean,nir_count,nir_sum,nir_mean
6391,4713,68,43,2500,407892,163.1568,2500,416425,166.57,2500,389516,155.8064,2500,449994,179.9976


In [ ]:
# result_df.to_csv('0_radii_before_after_clean.csv')

# Populate tree patches into arrays

In [ ]:
result_df = pd.read_csv('/content/drive/MyDrive/Year 2/Fall 2025/HONOR 3700/Data/0/Trees ML/0_radii_before_after_clean.csv')

In [ ]:
result_df = result_df.drop(columns=['Unnamed: 0'])

In [ ]:
result_df

,grid_id,radii_id,before_red,after_red,before_green,after_green,before_blue,after_blue,before_nir,after_nir
0,4713,1,163.156800,162.662876,166.570000,166.190089,155.806400,155.464257,179.997600,179.901706
1,4714,1,176.186624,175.332369,176.368843,175.638280,165.299159,164.636627,180.563476,180.420835
2,4712,4,163.377600,162.731011,165.856800,164.898028,156.722800,155.711708,182.564000,180.994964
3,4713,4,163.156800,162.956698,166.570000,166.292594,155.806400,155.537030,179.997600,179.519628
4,4712,5,163.377600,163.467695,165.856800,165.871613,156.722800,156.484368,182.564000,181.899125
...,...,...,...,...,...,...,...,...,...,...
6182,6798,110208,132.549600,135.961933,136.632400,139.340462,132.030800,134.446108,141.544800,140.903764
6183,6906,110208,115.277600,115.754272,124.586400,124.966640,114.270000,114.456062,166.697600,167.005289
6184,5706,110290,182.357000,182.491341,185.326113,185.458317,182.846771,182.996375,171.239471,171.436569
6185,5706,110291,182.357000,182.570508,185.326113,185.512490,182.846771,183.055197,171.239471,171.325141


In [ ]:
radii_to_grid_df.columns

Index(['radii_id', 'grid_id'], dtype='object')

In [ ]:
zonal_stats_df.columns

Index(['grid_id', 'row_index', 'col_index', 'red_count', 'red_sum', 'red_mean',
       'green_count', 'green_sum', 'green_mean', 'blue_count', 'blue_sum',
       'blue_mean', 'nir_count', 'nir_sum', 'nir_mean'],
      dtype='object')

In [ ]:
def build_center_index(patches):
    return {patch[2, 2]: patch for patch in patches}


def build_zonal_lookup(zonal_stats_df):
    return zonal_stats_df.set_index("grid_id").to_dict("index")


def build_radii_to_grid_lookup(radii_to_grid_df):
    return radii_to_grid_df.set_index("radii_id")["grid_id"].to_dict()


def get_patch_by_center(center_value, center_index):
    """
    Fetch the 5x5 patch given a center value.
    Returns None if not found.
    """
    return center_index.get(center_value, None)

In [ ]:
center_index = build_center_index(patches_0)

In [ ]:
patch = get_patch_by_center(4713, center_index)

if patch is not None:
    print(patch)
    print(patch.shape)
else:
    print("Not found")

[[4495 4603 4711 4819 4927]
 [4496 4604 4712 4820 4928]
 [4497 4605 4713 4821 4929]
 [4498 4606 4714 4822 4930]
 [4499 4607 4715 4823 4931]]
(5, 5)


In [ ]:
result_df[result_df['radii_id'] == 1]

,grid_id,radii_id,before_red,after_red,before_green,after_green,before_blue,after_blue,before_nir,after_nir
0,4713,1,163.156800,162.662876,166.570000,166.190089,155.806400,155.464257,179.997600,179.901706
1,4714,1,176.186624,175.332369,176.368843,175.638280,165.299159,164.636627,180.563476,180.420835


In [ ]:
BANDS = ["red", "green", "blue", "nir"]

In [ ]:
def build_result_array(
    result_df,
    radii_to_grid_df,
    zonal_stats_df,
    patches_tree_0
):
    radii_ids = []
    # --- Precompute lookups ---
    center_index = build_center_index(patches_tree_0)
    zonal_lookup = build_zonal_lookup(zonal_stats_df)
    radii_to_grid = build_radii_to_grid_lookup(radii_to_grid_df)

    unique_radii = result_df["radii_id"].unique()
    n = len(unique_radii)

    # Output: (N, 2, 4, 5, 5)
    output = np.zeros((n, 2, 4, 5, 5), dtype=float)

    for i, radii_id in enumerate(unique_radii):
        radii_ids.append(radii_id)
        # --- Step 1: get center grid_id ---
        center_grid_id = radii_to_grid[radii_id]

        # --- Step 2: get 5x5 patch of grid_ids ---
        patch = center_index.get(center_grid_id)
        if patch is None:
            continue  # or raise error if this should never happen

        # --- Step 3: subset result_df for this radii_id ---
        subset = result_df[result_df["radii_id"] == radii_id]
        subset_lookup = subset.set_index("grid_id").to_dict("index")

        # --- Step 4: fill cubes ---
        for r in range(5):
            for c in range(5):
                gid = patch[r, c]

                if gid in subset_lookup:
                    row = subset_lookup[gid]

                    for b_idx, band in enumerate(BANDS):
                        output[i, 0, b_idx, r, c] = row[f"before_{band}"]
                        output[i, 1, b_idx, r, c] = row[f"after_{band}"]

                else:
                    zonal = zonal_lookup[gid]

                    for b_idx, band in enumerate(BANDS):
                        val = zonal[f"{band}_mean"]
                        output[i, 0, b_idx, r, c] = val
                        output[i, 1, b_idx, r, c] = val

    return output, radii_ids

In [ ]:
output, radii_ids = build_result_array(
    result_df,
    radii_to_grid_df,
    zonal_stats_df,
    patches_0
)

In [ ]:
output.shape

(4099, 2, 4, 5, 5)

In [ ]:
radii_ids[0:5]

[np.int64(1), np.int64(4), np.int64(5), np.int64(7), np.int64(8)]

In [ ]:
output[0][0]

array([[[184.90828995, 189.6652    , 163.3776    , 240.54265118,
         225.0968    ],
        [189.20704846, 177.1932    , 163.1568    , 225.64837805,
         237.4172    ],
        [161.60649819, 171.0845014 , 176.18662395, 192.80986763,
         179.93592311],
        [192.44573488, 180.218     , 170.134     , 186.94152984,
         185.6152    ],
        [179.43772527, 166.0896    , 168.8668    , 181.12695234,
         194.6792    ]],

       [[180.42571085, 189.008     , 165.8568    , 238.10252303,
         222.5528    ],
        [185.17541049, 173.8568    , 166.57      , 225.50220264,
         236.8428    ],
        [161.48094665, 167.59711654, 176.36884261, 196.4749298 ,
         184.00480577],
        [189.68402082, 176.812     , 170.944     , 187.47937525,
         185.004     ],
        [175.29675611, 165.978     , 169.8168    , 181.02162595,
         190.0892    ]],

       [[168.91589908, 180.6984    , 156.7228    , 230.76211454,
         213.63      ],
        [173.2142

In [ ]:
output[0][1]

array([[[184.90828995, 189.6652    , 163.3776    , 240.54265118,
         225.0968    ],
        [189.20704846, 177.1932    , 162.66287571, 225.64837805,
         237.4172    ],
        [161.60649819, 171.0845014 , 175.33236875, 192.80986763,
         179.93592311],
        [192.44573488, 180.218     , 170.134     , 186.94152984,
         185.6152    ],
        [179.43772527, 166.0896    , 168.8668    , 181.12695234,
         194.6792    ]],

       [[180.42571085, 189.008     , 165.8568    , 238.10252303,
         222.5528    ],
        [185.17541049, 173.8568    , 166.19008936, 225.50220264,
         236.8428    ],
        [161.48094665, 167.59711654, 175.63828028, 196.4749298 ,
         184.00480577],
        [189.68402082, 176.812     , 170.944     , 187.47937525,
         185.004     ],
        [175.29675611, 165.978     , 169.8168    , 181.02162595,
         190.0892    ]],

       [[168.91589908, 180.6984    , 156.7228    , 230.76211454,
         213.63      ],
        [173.2142

# Transform tree patches

In [ ]:
landsat_blue_mean = predict_df['Blue'].mean()
landsat_red_mean = predict_df['Red'].mean()
landsat_green_mean = predict_df['Green'].mean()
landsat_nir_mean = predict_df['NIR'].mean()

landsat_blue_std = predict_df['Blue'].std()
landsat_red_std = predict_df['Red'].std()
landsat_green_std = predict_df['Green'].std()
landsat_nir_std = predict_df['NIR'].std()

In [ ]:
# take only the first item in the pair
data = output[:, 0, :, :, :]   # shape: (4099, 4, 5, 5)

# compute mean and std per band
means = data.mean(axis=(0, 2, 3))  # shape: (4,)
stds  = data.std(axis=(0, 2, 3))   # shape: (4,)

print("Means:", means)
print("Stds:", stds)

Means: [135.81638956 138.36910935 131.27705554 141.931442  ]
Stds: [59.3799442  59.02658933 56.60529698 60.53267541]


In [ ]:
naip_red_mean = means[0]
naip_blue_mean = means[1]
naip_green_mean = means[2]
naip_nir_mean = means[3]

naip_red_std = stds[0]
naip_blue_std = stds[1]
naip_green_std = stds[2]
naip_nir_std = stds[3]

In [ ]:
import numpy as np

# NAIP stats (from your computed means/stds)
naip_means = np.array([
    naip_red_mean,
    naip_green_mean,
    naip_blue_mean,
    naip_nir_mean
])

naip_stds = np.array([
    naip_red_std,
    naip_green_std,
    naip_blue_std,
    naip_nir_std
])

# Landsat stats (from dataframe)
landsat_means = np.array([
    landsat_red_mean,
    landsat_green_mean,
    landsat_blue_mean,
    landsat_nir_mean
])

landsat_stds = np.array([
    landsat_red_std,
    landsat_green_std,
    landsat_blue_std,
    landsat_nir_std
])

In [ ]:
# reshape to broadcast over (4099, 2, 4, 5, 5)
naip_means = naip_means.reshape(1, 1, 4, 1, 1)
naip_stds  = naip_stds.reshape(1, 1, 4, 1, 1)

landsat_means = landsat_means.reshape(1, 1, 4, 1, 1)
landsat_stds  = landsat_stds.reshape(1, 1, 4, 1, 1)

# apply transformation
output_normalized = (
    ((output - naip_stds) / naip_means) * landsat_stds
) + landsat_means

In [ ]:
output.shape

(4099, 2, 4, 5, 5)

In [ ]:
output_normalized.shape

(4099, 2, 4, 5, 5)

In [ ]:
output[0][0][0][0]

array([184.90828995, 189.6652    , 163.3776    , 240.54265118,
       225.0968    ])

In [ ]:
output_normalized[0][0][0][0]

array([0.23272257, 0.23543032, 0.22046679, 0.26439097, 0.25559882])

# Compute time embeddings

## Calculate NAIP time embedding

In [ ]:
target_date

Timestamp('2024-07-08 00:00:00')

In [ ]:
first_date = predict_df['time'].min()
last_date = predict_df['time'].max()

In [ ]:
first_date

Timestamp('1982-11-19 17:36:28')

In [ ]:
last_date

Timestamp('2026-03-25 18:07:55')

In [ ]:
closest_date

Timestamp('2024-06-23 18:07:27')

In [ ]:
target_date - closest_date

Timedelta('14 days 05:52:33')

In [ ]:
naip_embedding = get_one_time_embedding(
    first_time=first_date,
    last_time=closest_date,
    time=target_date
)

In [ ]:
naip_embedding

array([ 2.02400000e+03,  7.00000000e+00,  1.90000000e+02, -1.28748177e-01,
        1.40000000e+01,  1.52060000e+04])

# Add NAIP embeddings

In [ ]:
len(cubes_trees_0), len(targets_trees_0), len(times_trees_0)

(3848, 3848, 3848)

In [ ]:
tree_patches = patches_0[0:len(cubes_trees_0)]

In [ ]:
tree_patches.shape

(3848, 5, 5)

## Add time embeddings

In [ ]:
type(target_date)

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
type(times_trees_0[0][0])

numpy.datetime64

In [ ]:
target_date_np = target_date.to_datetime64()

In [ ]:
type(target_date_np)

numpy.datetime64

In [ ]:
len(times_trees_0)

3848

In [ ]:
times_trees_0[0][0]

np.datetime64('1984-07-30T01:40:17.000000000')

In [ ]:
target_date_np

np.datetime64('2024-07-08T00:00:00.000000000')

In [ ]:
for i in range(len(times_trees_0)):
    times_trees_0[i] = np.append(times_trees_0[i], target_date_np)

In [ ]:
len(times_trees_0)

3848

In [ ]:
times_trees_0[0].shape

(366,)

In [ ]:
times_trees_0[0][364]

np.datetime64('2024-06-18T02:10:12.000000000')

In [ ]:
times_trees_0[0][365]

np.datetime64('2024-07-08T00:00:00.000000000')

In [ ]:
time_embeddings_trees = []

In [ ]:
transform_times(time_embeddings_trees, times_trees_0)

In [ ]:
len(time_embeddings_trees)

3848

In [ ]:
len(time_embeddings_0[0])

796

In [ ]:
len(time_embeddings_trees[0])

366

## Add garbage target value

In [ ]:
targets_trees_0[0].shape

(365,)

In [ ]:
for i in range(len(targets_trees_0)):
    targets_trees_0[i] = np.append(targets_trees_0[i], -1)

In [ ]:
targets_trees_0[0].shape

(366,)

## Add raster bands

In [ ]:
len(cubes_trees_0)

3848

In [ ]:
cubes_trees_0[0].shape

(365, 4, 5, 5)

In [ ]:
tree_patches.shape

(3848, 5, 5)

In [ ]:
tree_patches[0]

array([[ 92, 200, 308, 416, 524],
       [ 93, 201, 309, 417, 525],
       [ 94, 202, 310, 418, 526],
       [ 95, 203, 311, 419, 527],
       [ 96, 204, 312, 420, 528]])

In [ ]:
tree_patches.max()

np.int64(13709)

In [ ]:
output_normalized.shape

(4099, 2, 4, 5, 5)

In [ ]:
len(result_df["radii_id"].unique())

4099

In [ ]:
radii_df[['radii_id', 'grid_id']]

,radii_id,grid_id
0,1,4714.0
1,4,4712.0
2,5,4712.0
3,7,4711.0
4,8,4711.0
...,...,...
4385,108092,8954.0
4386,110208,6798.0
4387,110290,5706.0
4388,110291,5706.0


In [ ]:
radii_df['grid_id'].max()

13709.0

In [ ]:
samples = []  # will grow dynamically

# Precompute lookup
tree_centers = tree_patches[:, 2, 2]
center_to_index = {int(val): idx for idx, val in enumerate(tree_centers)}

radii_ids = result_df["radii_id"].unique()

In [ ]:
valid_radii_ids = []

In [ ]:
for i, radii_id in enumerate(radii_ids):

    # --- Get grid_id safely ---
    grid_match = radii_df.loc[radii_df["radii_id"] == radii_id, "grid_id"]

    if grid_match.empty:
        continue  # skip invalid

    grid_id = int(grid_match.values[0])

    # --- Check if grid_id exists in tree_patches ---
    tree_idx = center_to_index.get(grid_id, None)
    if tree_idx is None:
        continue  # skip invalid

    # --- Bounds check for cubes_trees_0 ---
    if tree_idx >= len(cubes_trees_0):
        continue  # avoid index error

    cubes = cubes_trees_0[tree_idx]  # (n, 4, 5, 5)

    # --- Validate cube shape ---
    if cubes.ndim != 4 or cubes.shape[1:] != (4, 5, 5):
        continue  # malformed data

    if cubes.shape[0] < 99:
        continue  # not enough history

    cubes_99 = cubes[-99:]  # (99, 4, 5, 5)

    # --- Check output_normalized alignment ---
    if i >= len(output_normalized):
        continue  # prevent out-of-bounds

    current = output_normalized[i]  # (2, 4, 5, 5)

    if current.shape != (2, 4, 5, 5):
        continue  # unexpected shape

    # --- Build sample ---
    sample = np.zeros((2, 100, 4, 5, 5), dtype=output_normalized.dtype)

    for pair in range(2):
        sample[pair, :99] = cubes_99
        sample[pair, 99] = current[pair]

    samples.append(sample)
    valid_radii_ids.append(radii_id)

In [ ]:
# --- Final stack ---
if len(samples) == 0:
    raise ValueError("No valid samples found")

final_output = np.stack(samples, axis=0)

print("Final shape:", final_output.shape)

Final shape: (2187, 2, 100, 4, 5, 5)


In [ ]:
len(valid_radii_ids)

2187

In [ ]:
valid_radii_ids[0:5]

[np.int64(46), np.int64(48), np.int64(52), np.int64(1031), np.int64(1034)]